// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf Java Version: 4.27.3

package org.learn.realtimeim.protocol.message;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.learn.realtimeim.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.learn.realtimeim.Message.ContentType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.org.learn.realtimeim.Message.ContentType type = 1;</code>
   * @return The type.
   */
  org.learn.realtimeim.protocol.message.Message.ContentType getType();

  /**
   * <code>string senderId = 2;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string senderId = 2;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string chatId = 3;</code>
   * @return The chatId.
   */
  java.lang.String getChatId();
  /**
   * <code>string chatId = 3;</code>
   * @return The bytes for chatId.
   */
  com.google.protobuf.ByteString
      getChatIdBytes();

  /**
   * <code>string content = 4;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 4;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
